// Mock Data for PCAP Network Analyzer Frontend Demo
import type {
  Packet,
  PacketSummary,
  VulnerabilityAlert,
  VulnerabilityResponse,
  PortInfo,
  ExtractedImage,
  AgentQueryResponse,
  ChatMessage,
} from './types';

// ============ MOCK PACKETS ============

export const mockPackets: Packet[] = [
  {
    id: 0,
    timestamp: 1714473600.123,
    src_ip: '192.168.1.100',
    dst_ip: '8.8.8.8',
    src_port: 54321,
    dst_port: 53,
    protocol: 'DNS',
    length: 64,
    ttl: 64,
    flags: null,
    payload_preview: '',
  },
  {
    id: 1,
    timestamp: 1714473600.456,
    src_ip: '192.168.1.100',
    dst_ip: '142.250.185.78',
    src_port: 54322,
    dst_port: 443,
    protocol: 'HTTPS',
    length: 1420,
    ttl: 64,
    flags: 'PA',
    payload_preview: '',
  },
  {
    id: 2,
    timestamp: 1714473601.789,
    src_ip: '10.0.0.50',
    dst_ip: '192.168.1.100',
    src_port: 21,
    dst_port: 49876,
    protocol: 'FTP',
    length: 78,
    ttl: 128,
    flags: 'SA',
    payload_preview: '220 ProFTPD 1.3.5 Server ready.',
  },
  {
    id: 3,
    timestamp: 1714473602.100,
    src_ip: '192.168.1.100',
    dst_ip: '10.0.0.50',
    src_port: 49876,
    dst_port: 21,
    protocol: 'FTP',
    length: 45,
    ttl: 64,
    flags: 'PA',
    payload_preview: 'USER admin',
  },
  {
    id: 4,
    timestamp: 1714473602.500,
    src_ip: '192.168.1.100',
    dst_ip: '10.0.0.50',
    src_port: 49876,
    dst_port: 21,
    protocol: 'FTP',
    length: 45,
    ttl: 64,
    flags: 'PA',
    payload_preview: 'PASS secretpassword123',
  },
  {
    id: 5,
    timestamp: 1714473603.200,
    src_ip: '172.16.0.25',
    dst_ip: '192.168.1.100',
    src_port: 23,
    dst_port: 45678,
    protocol: 'TELNET',
    length: 120,
    ttl: 64,
    flags: 'PA',
    payload_preview: 'Login: root\nPassword: admin123',
  },
  {
    id: 6,
    timestamp: 1714473604.300,
    src_ip: '192.168.1.100',
    dst_ip: '151.101.1.140',
    src_port: 54330,
    dst_port: 80,
    protocol: 'HTTP',
    length: 256,
    ttl: 64,
    flags: 'PA',
    payload_preview: 'GET /api/data HTTP/1.1\nAuthorization: Basic dXNlcjpwYXNz',
  },
  {
    id: 7,
    timestamp: 1714473605.100,
    src_ip: '192.168.1.100',
    dst_ip: '203.0.113.50',
    src_port: 54340,
    dst_port: 3306,
    protocol: 'MYSQL',
    length: 200,
    ttl: 64,
    flags: 'S',
    payload_preview: '',
  },
  {
    id: 8,
    timestamp: 1714473606.200,
    src_ip: '192.168.1.100',
    dst_ip: '93.184.216.34',
    src_port: 54350,
    dst_port: 443,
    protocol: 'HTTPS',
    length: 1500,
    ttl: 64,
    flags: 'PA',
    payload_preview: '',
  },
  {
    id: 9,
    timestamp: 1714473607.300,
    src_ip: '45.33.32.156',
    dst_ip: '192.168.1.100',
    src_port: 3389,
    dst_port: 49200,
    protocol: 'RDP',
    length: 512,
    ttl: 48,
    flags: 'S',
    payload_preview: '',
  },
  {
    id: 10,
    timestamp: 1714473608.400,
    src_ip: '192.168.1.100',
    dst_ip: '8.8.4.4',
    src_port: 54360,
    dst_port: 53,
    protocol: 'DNS',
    length: 72,
    ttl: 64,
    flags: null,
    payload_preview: '',
  },
  {
    id: 11,
    timestamp: 1714473609.500,
    src_ip: '192.168.1.100',
    dst_ip: '185.199.108.153',
    src_port: 54370,
    dst_port: 443,
    protocol: 'HTTPS',
    length: 1200,
    ttl: 64,
    flags: 'PA',
    payload_preview: '',
  },
  {
    id: 12,
    timestamp: 1714473610.600,
    src_ip: '10.0.0.100',
    dst_ip: '192.168.1.100',
    src_port: 161,
    dst_port: 49300,
    protocol: 'SNMP',
    length: 150,
    ttl: 64,
    flags: null,
    payload_preview: 'public',
  },
  {
    id: 13,
    timestamp: 1714473611.700,
    src_ip: '192.168.1.100',
    dst_ip: '104.16.132.229',
    src_port: 54380,
    dst_port: 443,
    protocol: 'HTTPS',
    length: 800,
    ttl: 64,
    flags: 'PA',
    payload_preview: '',
  },
  {
    id: 14,
    timestamp: 1714473612.800,
    src_ip: '192.168.1.100',
    dst_ip: '10.0.0.50',
    src_port: 54390,
    dst_port: 445,
    protocol: 'SMB',
    length: 350,
    ttl: 64,
    flags: 'PA',
    payload_preview: '',
  },
];

// ============ MOCK SUMMARY ============

export const mockSummary: PacketSummary = {
  total_packets: 2847,
  protocols: {
    HTTPS: 1245,
    HTTP: 456,
    DNS: 389,
    FTP: 124,
    TELNET: 67,
    SSH: 89,
    SMTP: 145,
    MYSQL: 34,
    RDP: 23,
    SNMP: 45,
    SMB: 78,
    UDP: 152,
  },
  duration_seconds: 300,
  total_bytes: 15728640,
  time_range: {
    start: 1714473600,
    end: 1714473900,
  },
};

// ============ MOCK VULNERABILITIES ============

export const mockVulnerabilities: VulnerabilityResponse = {
  alerts: [
    {
      layer: 1,
      risk: 'CRITICAL',
      protocol: 'TELNET',
      port: 23,
      src_ip: '172.16.0.25',
      dst_ip: '192.168.1.100',
      reason: 'Completely unencrypted. All data including passwords visible.',
    },
    {
      layer: 1,
      risk: 'HIGH',
      protocol: 'FTP',
      port: 21,
      src_ip: '10.0.0.50',
      dst_ip: '192.168.1.100',
      reason: 'Transmits credentials in plaintext. Use SFTP instead.',
    },
    {
      layer: 2,
      risk: 'CRITICAL',
      src_ip: '192.168.1.100',
      dst_ip: '10.0.0.50',
      port: 21,
      reason: 'FTP Password in plaintext',
      payload_snippet: 'PASS secretpassword123',
    },
    {
      layer: 2,
      risk: 'CRITICAL',
      src_ip: '192.168.1.100',
      dst_ip: '151.101.1.140',
      port: 80,
      reason: 'HTTP Basic Auth (base64 encoded)',
      payload_snippet: 'Authorization: Basic dXNlcjpwYXNz',
    },
    {
      layer: 1,
      risk: 'HIGH',
      protocol: 'MYSQL',
      port: 3306,
      src_ip: '192.168.1.100',
      dst_ip: '203.0.113.50',
      reason: 'Database exposed. Should never be internet-facing.',
    },
    {
      layer: 1,
      risk: 'HIGH',
      protocol: 'RDP',
      port: 3389,
      src_ip: '45.33.32.156',
      dst_ip: '192.168.1.100',
      reason: 'BlueKeep CVE-2019-0708. Frequent ransomware entry point.',
    },
    {
      layer: 1,
      risk: 'HIGH',
      protocol: 'SNMP',
      port: 161,
      src_ip: '10.0.0.100',
      dst_ip: '192.168.1.100',
      reason: 'v1/v2 have no encryption. Community strings in plaintext.',
    },
    {
      layer: 1,
      risk: 'HIGH',
      protocol: 'SMB',
      port: 445,
      src_ip: '192.168.1.100',
      dst_ip: '10.0.0.50',
      reason: 'EternalBlue (MS17-010) target. Keep patched.',
    },
    {
      layer: 1,
      risk: 'MEDIUM',
      protocol: 'HTTP',
      port: 80,
      src_ip: '192.168.1.100',
      dst_ip: '151.101.1.140',
      reason: 'Unencrypted web traffic. MITM attack possible.',
    },
    {
      layer: 3,
      risk: 'HIGH',
      ip: '45.33.32.156',
      open_ports: [22, 80, 443, 3389],
      cves: ['CVE-2019-0708', 'CVE-2020-0609'],
      hostnames: ['scanme.nmap.org'],
      reason: 'Host has 2 known CVEs',
    },
  ],
  summary: {
    critical: 3,
    high: 5,
    medium: 1,
    low: 0,
  },
};

// ============ MOCK PORT INTELLIGENCE ============

export const mockPortIntel: PortInfo[] = [
  {
    port: 21,
    name: 'FTP',
    description: 'File Transfer Protocol - Used for transferring files between systems',
    risk: 'HIGH',
    secure_alternative: 'SFTP (port 22)',
    common_uses: ['File uploads/downloads', 'Legacy systems', 'Batch file transfers'],
    vulnerabilities: [
      'Credentials sent in plaintext',
      'Vulnerable to brute force attacks',
      'FTP bounce attacks',
      'Anonymous access misconfiguration',
    ],
    recommendations: [
      'Use SFTP instead',
      'Disable anonymous access',
      'Implement strong passwords',
      'Use TLS/SSL encryption (FTPS)',
    ],
  },
  {
    port: 22,
    name: 'SSH',
    description: 'Secure Shell - Encrypted remote administration protocol',
    risk: 'SECURE',
    secure_alternative: 'Already secure',
    common_uses: ['Remote server administration', 'Secure file transfers', 'Port forwarding'],
    vulnerabilities: [
      'Brute force attacks if password auth enabled',
      'Vulnerable key exposure',
    ],
    recommendations: [
      'Use key-based authentication',
      'Disable password authentication',
      'Use fail2ban for brute force protection',
      'Keep SSH server updated',
    ],
  },
  {
    port: 23,
    name: 'Telnet',
    description: 'Telnet - Unencrypted remote terminal protocol',
    risk: 'CRITICAL',
    secure_alternative: 'SSH (port 22)',
    common_uses: ['Legacy network equipment', 'Embedded devices', 'IoT devices'],
    vulnerabilities: [
      'No encryption - all data visible',
      'Credentials sent in plaintext',
      'Session hijacking',
      'Man-in-the-middle attacks',
    ],
    recommendations: [
      'Replace with SSH immediately',
      'Disable on all systems',
      'Use VPN if remote access required',
      'Audit for any remaining Telnet services',
    ],
  },
  {
    port: 53,
    name: 'DNS',
    description: 'Domain Name System - Resolves domain names to IP addresses',
    risk: 'MEDIUM',
    secure_alternative: 'DNS over HTTPS (DoH) / DNSSEC',
    common_uses: ['Domain resolution', 'Service discovery', 'Load balancing'],
    vulnerabilities: [
      'DNS cache poisoning',
      'DNS amplification DDoS',
      'Zone transfer attacks',
      'DNS tunneling',
    ],
    recommendations: [
      'Implement DNSSEC',
      'Restrict zone transfers',
      'Use rate limiting',
      'Monitor for suspicious queries',
    ],
  },
  {
    port: 80,
    name: 'HTTP',
    description: 'Hypertext Transfer Protocol - Unencrypted web traffic',
    risk: 'MEDIUM',
    secure_alternative: 'HTTPS (port 443)',
    common_uses: ['Web browsing', 'APIs', 'Web applications'],
    vulnerabilities: [
      'No encryption',
      'Man-in-the-middle attacks',
      'Session hijacking',
      'Data interception',
    ],
    recommendations: [
      'Redirect all HTTP to HTTPS',
      'Implement HSTS',
      'Use TLS 1.3',
      'Get certificates from trusted CA',
    ],
  },
  {
    port: 443,
    name: 'HTTPS',
    description: 'HTTP Secure - Encrypted web traffic with TLS/SSL',
    risk: 'SECURE',
    secure_alternative: 'Already secure',
    common_uses: ['Secure web browsing', 'E-commerce', 'Online banking'],
    vulnerabilities: [
      'Outdated TLS versions',
      'Weak cipher suites',
      'Certificate issues',
    ],
    recommendations: [
      'Use TLS 1.3',
      'Disable old protocols (SSL, TLS 1.0, 1.1)',
      'Implement HSTS',
      'Use strong cipher suites',
    ],
  },
  {
    port: 3306,
    name: 'MySQL',
    description: 'MySQL Database Server - Relational database management system',
    risk: 'HIGH',
    secure_alternative: 'Bind to localhost only, use SSH tunnel',
    common_uses: ['Web application databases', 'Content management', 'E-commerce'],
    vulnerabilities: [
      'Brute force attacks',
      'SQL injection if app vulnerable',
      'Default root access',
      'Unencrypted data transfer',
    ],
    recommendations: [
      'Never expose to internet',
      'Use strong passwords',
      'Implement connection pooling',
      'Enable SSL for connections',
    ],
  },
  {
    port: 3389,
    name: 'RDP',
    description: 'Remote Desktop Protocol - Windows remote desktop access',
    risk: 'HIGH',
    secure_alternative: 'VPN + NLA required',
    common_uses: ['Remote administration', 'Help desk support', 'Remote work'],
    vulnerabilities: [
      'BlueKeep (CVE-2019-0708)',
      'Brute force attacks',
      'Ransomware entry point',
      'Credential stuffing',
    ],
    recommendations: [
      'Use VPN for access',
      'Enable Network Level Authentication',
      'Strong password policy',
      'Keep systems patched',
    ],
  },
  {
    port: 6379,
    name: 'Redis',
    description: 'Redis - In-memory data structure store',
    risk: 'CRITICAL',
    secure_alternative: 'Bind to localhost only, enable AUTH',
    common_uses: ['Caching', 'Session storage', 'Message queues', 'Real-time analytics'],
    vulnerabilities: [
      'No authentication by default',
      'Remote code execution possible',
      'Data exfiltration',
      'Cryptojacking target',
    ],
    recommendations: [
      'Never expose to internet',
      'Enable AUTH',
      'Use TLS encryption',
      'Implement firewall rules',
    ],
  },
  {
    port: 27017,
    name: 'MongoDB',
    description: 'MongoDB - NoSQL document database',
    risk: 'HIGH',
    secure_alternative: 'Bind to localhost only, enable auth',
    common_uses: ['Web applications', 'Big data', 'Content management', 'IoT'],
    vulnerabilities: [
      'Default no authentication',
      'Data breaches common',
      'Ransomware target',
      'Injection attacks',
    ],
    recommendations: [
      'Enable authentication',
      'Use TLS/SSL',
      'Implement role-based access',
      'Regular backups',
    ],
  },
];

// ============ MOCK IMAGES ============

export const mockImages: ExtractedImage[] = [
  {
    filename: 'image_001.jpg',
    method: 'dpkt',
    size: 45678,
    content_type: 'image/jpeg',
    url: 'https://picsum.photos/seed/pcap1/800/600',
  },
  {
    filename: 'image_002.png',
    method: 'dpkt',
    size: 128456,
    content_type: 'image/png',
    url: 'https://picsum.photos/seed/pcap2/800/600',
  },
  {
    filename: 'image_003.jpg',
    method: 'magic',
    size: 67890,
    content_type: 'image/jpeg',
    url: 'https://picsum.photos/seed/pcap3/800/600',
  },
  {
    filename: 'image_004.gif',
    method: 'dpkt',
    size: 23456,
    content_type: 'image/gif',
    url: 'https://picsum.photos/seed/pcap4/800/600',
  },
  {
    filename: 'image_005.png',
    method: 'magic',
    size: 89012,
    content_type: 'image/png',
    url: 'https://picsum.photos/seed/pcap5/800/600',
  },
  {
    filename: 'image_006.jpg',
    method: 'dpkt',
    size: 156789,
    content_type: 'image/jpeg',
    url: 'https://picsum.photos/seed/pcap6/800/600',
  },
];

// ============ MOCK AGENT RESPONSES ============

export const mockAgentResponses: AgentQueryResponse[] = [
  {
    tool_called: 'filter_by_port',
    parameters: { ports: [21] },
    result: { packets: mockPackets.filter(p => p.src_port === 21 || p.dst_port === 21) },
    response: 'Found 4 packets on port 21 (FTP). 2 packets show plaintext credentials being transmitted.',
  },
  {
    tool_called: 'find_credentials',
    parameters: {},
    result: { count: 4, locations: ['FTP', 'Telnet', 'HTTP Basic Auth'] },
    response: '⚠️ Found 4 instances of plaintext credentials:\n• FTP: USER/PASS commands detected\n• Telnet: Login credentials visible\n• HTTP: Basic Auth header (base64 encoded)',
  },
  {
    tool_called: 'detect_port_scan',
    parameters: {},
    result: { is_scan: false, suspicious_ips: [] },
    response: 'No port scanning activity detected. Traffic patterns appear normal.',
  },
  {
    tool_called: 'get_vulnerability_report',
    parameters: {},
    result: mockVulnerabilities,
    response: 'Vulnerability scan complete. Found 3 CRITICAL and 5 HIGH severity issues. Most critical: Telnet credentials exposed.',
  },
];

// ============ MOCK CHAT MESSAGES ============

export const mockChatMessages: ChatMessage[] = [
  {
    id: '1',
    role: 'user',
    content: 'Show me all FTP traffic',
    timestamp: new Date(Date.now() - 60000),
  },
  {
    id: '2',
    role: 'assistant',
    content: 'Found 4 FTP packets in the capture. Port 21 traffic detected with plaintext USER/PASS commands visible.',
    toolCalled: 'filter_by_port',
    toolParams: { ports: [21] },
    timestamp: new Date(Date.now() - 58000),
  },
  {
    id: '3',
    role: 'user',
    content: 'Find any credentials in the traffic',
    timestamp: new Date(Date.now() - 45000),
  },
  {
    id: '4',
    role: 'assistant',
    content: '⚠️ **Security Alert**: Found 4 instances of plaintext credentials:\n\n1. **FTP**: `PASS secretpassword123` visible in packet #4\n2. **Telnet**: `Password: admin123` visible in packet #5\n3. **HTTP Basic Auth**: Base64 encoded credentials in packet #6\n\n**Recommendation**: Immediately rotate all exposed credentials and migrate to encrypted protocols.',
    toolCalled: 'find_credentials',
    toolParams: {},
    timestamp: new Date(Date.now() - 43000),
  },
];

// ============ MOCK SESSION ============

export const mockSession = {
  session_id: 'demo-session-001',
  filename: 'network_capture.pcap',
  uploaded_at: new Date(),
  summary: mockSummary,
  packets: mockPackets,
  vulnerabilities: mockVulnerabilities.alerts,
  images: mockImages,
};

// ============ PROTOCOL COLORS ============

export const protocolColors: Record<string, string> = {
  HTTPS: '#00FF88',
  HTTP: '#FFB800',
  DNS: '#00D4FF',
  FTP: '#FF3B5C',
  TELNET: '#FF0000',
  SSH: '#7B2FFF',
  SMTP: '#FF8C00',
  MYSQL: '#FF6B6B',
  RDP: '#FF4757',
  SNMP: '#FFA502',
  SMB: '#FF6348',
  UDP: '#70A1FF',
  TCP: '#5352ED',
  ICMP: '#A4B0BE',
  UNKNOWN: '#636E72',
};
